indiGo.Web/Controllers/ServiceController.cs
using indiGo.Business.Repositories.Abstract;
using indiGo.Core.Entities;
using indiGo.Core.Identity;
using indiGo.Core.ViewModels;
using indiGo.Core.ViewModels.PageViewModels;
using indiGo.Data.Identity;
using indiGo.Web.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace indiGo.Web.Controllers;

[Authorize(Roles = "ELECTRICALSERVICE,GASSERVICE,PLUMBINGSERVICE")]
public class ServiceController : Controller
{
    private readonly IRepository<ServiceDemand, int> _serviceDemandRepository;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IRepository<Address, int> _addressRepository;
    private readonly IRepository<Product,int> _productRepository;
    private readonly IRepository<Receipt,int> _receiptRepository;
    private readonly IRepository<ReceiptDetail,int> _receiptDetailRepository;

    public ServiceController(IRepository<ServiceDemand, int> serviceDemandRepository, UserManager<ApplicationUser> userManager, IRepository<Address, int> addressRepository, IRepository<Product, int> productRepository, IRepository<Receipt, int> receiptRepository, IRepository<ReceiptDetail, int> receiptDetailRepository)
    {
        _serviceDemandRepository = serviceDemandRepository;
        _userManager = userManager;
        _addressRepository = addressRepository;
        _productRepository = productRepository;
        _receiptRepository = receiptRepository;
        _receiptDetailRepository = receiptDetailRepository;
    }

    [HttpGet]
    public IActionResult WaitingDemands()
    {
        var demands = _serviceDemandRepository.Get(x => x.ServiceId == HttpContext.GetUserId()).ToList();

        var model = new List<ServiceDemandViewModel>();
        demands.ForEach(x =>
        {
            if (x.Accepted)
            {
                return;
            }
            var address = _addressRepository.GetById(x.AddressId);
            model.Add(new ServiceDemandViewModel()
            {
                Id = x.Id,
                FirstName = x.FirstName,
                LastName = x.LastName,
                Address = address,
                AddressId = x.AddressId,
                Category = x.Category,
                CreatedAt = x.CreatedAt,
                PhoneNumber = x.PhoneNumber,
                TCKN = x.TCKN,
                Problem = x.Problem
            });
        });

        return View(model);
    }

    [HttpPost]
    public IActionResult TakeJob(int serviceId)
    {
        var demand = _serviceDemandRepository.GetById(serviceId);
        if (demand == null)
        {
            TempData["status"] = "fail";
        }
        else
        {
            demand.Accepted = true;
            _serviceDemandRepository.Save();
            TempData["status"] = "success";
        }
        return RedirectToAction("WaitingDemands");
    }

    [HttpGet]
    public IActionResult AcceptedDemands()
    {
        var demands = _serviceDemandRepository.Get(x => x.ServiceId == HttpContext.GetUserId() && !x.Receipted).ToList();
        var products = _productRepository.Get().ToList();

        var model = new AcceptedDemandsPageViewModel();
        
        demands.ForEach(x =>
        {
            if (!x.Accepted)
            {
                return;
            }
            var address = _addressRepository.GetById(x.AddressId);
            model.ServiceDemands.Add(new ServiceDemandViewModel()
            {
                Id = x.Id,
                FirstName = x.FirstName,
                LastName = x.LastName,
                Address = address,
                AddressId = x.AddressId,
                Category = x.Category,
                CreatedAt = x.CreatedAt,
                PhoneNumber = x.PhoneNumber,
                TCKN = x.TCKN,
                Problem = x.Problem
            });
        });

        products.ForEach(x =>
        {
            model.Products.Add(new ProductViewModel()
            {
                Id = x.Id,
                Category = x.Category,
                Name = x.Name,
                Price = x.Price
            });
        });

        return View(model);
    }

    [HttpPost]
    public IActionResult AcceptedDemands(DemandProductReceiptViewModel model)
    {
        var demand = _serviceDemandRepository.GetById(model.DemandId);
        var receipt = new Receipt()
        {
            DemandId = model.DemandId
        };

        _receiptRepository.Insert(receipt);
        _receiptRepository.Save();

        model.Products.ForEach(x =>
        {
            _receiptDetailRepository.Insert(new ReceiptDetail()
            {
                ProductId = x.Id, 
                ReceiptId = receipt.Id,
                Quantity = x.Quantity
            });
        });
        demand.Receipted = true;
        _receiptDetailRepository.Save();
        _serviceDemandRepository.Save();

        TempData["ReceiptCreated"] = "success";
        
        return RedirectToAction("AcceptedDemands");
    }

    [HttpGet]
    public IActionResult CompletedDemands()
    {
        var demands = _serviceDemandRepository.Get(x => x.ServiceId == HttpContext.GetUserId() && x.Receipted).ToList();
        
        var model = new List<CompletedDemandsPageViewModel>();

        demands.ForEach(x =>
        {
            var receipt = _receiptRepository.Get(y => y.DemandId == x.Id).FirstOrDefault();
            var details = _receiptDetailRepository.Get(y => y.ReceiptId == receipt.Id).ToList();
            model.Add(new CompletedDemandsPageViewModel()
            {
                ServiceDemand = new ServiceDemandViewModel()
                {
                    FirstName = x.FirstName,
                    LastName = x.LastName,
                    AddressId = x.AddressId,
                    Accepted = x.Accepted,
                    Category = x.Category,
                    Completed = x.Completed,
                    CreatedAt = x.CreatedAt,
                    Id = x.Id,
                    PhoneNumber = x.PhoneNumber,
                    Paid = x.Paid,
                    Problem = x.Problem,
                    ServiceId = x.ServiceId,
                    Receipted = x.Receipted,
                    TCKN = x.TCKN
                },
            });
            details.ForEach(y =>
            {
                var product = _productRepository.GetById(y.ProductId);
                model.Last().Products.Add(new ReceiptProductViewModel()
                {
                    Id = product.Id,
                    Price = product.Price,
                    Category = product.Category,
                    Name = product.Name,
                    Quantity = y.Quantity
                });
                model.Last().TotalPrice += Math.Round(y.Quantity * product.Price,2);
            });
            

        });

      
        return View(model);
    }

}

indiGo.Web/Views/Service/AcceptedDemands.cshtml
@model indiGo.Core.ViewModels.PageViewModels.AcceptedDemandsPageViewModel

<div class="col-lg-8 pb-5 pl-lg-5 offset-lg-2 mt-5">
    <h3 class="pb-4">Kabul Edilen İşler</h3>
    <div class="list-group">
        @if (Model != null)
        {
            @if (Model.ServiceDemands.Count != 0)
            {
                @foreach (var demand in Model.ServiceDemands)
                {
                    <div class="list-group-item list-group-item-action flex-column align-items-start servicesList">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1"><i class="fa fa-user"></i> @demand.FirstName @demand.LastName</h5>
                            <small>@demand.CreatedAt.ToShortDateString()</small>
                        </div>
                        @if (@demand.Category == "electric")
                        {
                            <i class="fa fa-plug text-primary"></i>
                            <span>Elektrik Tesisatı</span>
                        }
                        else if (@demand.Category == "gas")
                        {
                            <img src="../../fonts/CustomIcons/geyser.svg" style="margin-left: -3px" width="19px" height="19px" class="" />
                            <span>Doğalgaz Tesisatı</span>
                        }
                        else if (@demand.Category == "plumbing")
                        {
                            <img src="../../fonts/CustomIcons/water.svg" style="margin-left: -3px" width="18px" height="16px" />
                            <span>Su Tesisatı</span>
                        }
                        <div>
                            <i class="fa fa-exclamation d-inline" style="margin-left: 2px; margin-right: 2px"></i>
                            <p class="d-inline">@demand.Problem</p>
                        </div>
                        <div class="d-flex justify-content-between">
                            <div>
                                <svg class="" width="12px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M168.3 499.2C116.1 435 0 279.4 0 192C0 85.96 85.96 0 192 0C298 0 384 85.96 384 192C384 279.4 267 435 215.7 499.2C203.4 514.5 180.6 514.5 168.3 499.2H168.3zM192 256C227.3 256 256 227.3 256 192C256 156.7 227.3 128 192 128C156.7 128 128 156.7 128 192C128 227.3 156.7 256 192 256z" /></svg>
                                <span> @demand.Address.Neighborhood Mahallesi, @demand.Address.Street Sokağı/Caddesi, No:@demand.Address.ApartmentNo, Daire:@demand.Address.FlatNo, @demand.Address.District/@demand.Address.City </span>
                            </div>
                            <button data-id="@demand.Id" class="btn btn-sm btn-primary completeJob">
                                İşi Tamamla
                            </button>
                        </div>

                    </div>


                }
            }
            else
            {
                <p>Kabul Edilen İş Bulunmamaktadır.</p>
            }
        }
    </div>
</div>

<div class="modal fade" id="serviceModal" role="dialog" aria-labelledby="serviceModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">Yapılan İşlemleri ve Tutarlarını Giriniz.</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body px-3">
                <div class="form-row">
                    <div class="form-group col-md-6 mr-3" style="margin-bottom: 0 !important;">
                        <label>İş Kalemi</label>
                    </div>
                    <div class="form-group col-sm-3 " style="margin-bottom: 0 !important;">
                        <label>Adet</label>
                    </div>
                </div>
                <div class="d-flex justify-content-between" style="align-items: first baseline!important">
                    <select class="form-group custom-select col-md-6 mr-2 productSelect">
                        <option>Lütfen bir ürün seçiniz</option>
                        @foreach (var product in Model.Products)
                        {
                            <option value="@product.Id" data-price="@product.Price">@product.Name</option>
                        }
                    </select>
                    <input type="number" id="quantity" class="form-control col-sm-3 mr-2" placeholder="Adet" />
                    <div class="form-group">
                        <input id="addEntry" type="button" class="btn btn-sm btn-primary" value="Ekle" />
                    </div>
                </div>
                <div id="listContainer">
                    <h4 class="mt-3">Yapılan İşler</h4>
                    <p id="info">Herhangi ürün eklenmedi.</p>
                    <table id="productTable" class="table d-none">
                        <thead>
                            <tr>
                                <th scope="col">Ürün</th>
                                <th scope="col">Adet</th>
                                <th scope="col">Birim Fiyat</th>
                                <th scope="col">Toplam Fiyat</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody id="entryList">
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" data-dismiss="modal">İptal</button>
                <button class="btn btn-secondary" id="sendProducts">Yapılan işleri gönder</button>
            </div>
        </div>
    </div>
</div>


<script>
    var receipt = {demandId:"",products:[]};

    $(() => {
        if ("@TempData["ReceiptCreated"]" == "success") {
            toastr.success("Fatura gönderildi.");
        }
    });

    $(".completeJob").on("click",
        function() {
            Swal.fire({
                title: 'Bu işi tamamladınız mı?',
                icon: 'question',
                showCancelButton: true,
                confirmButtonColor: '#007c77',
                cancelButtonColor: '#ffc600',
                confirmButtonText: 'Tamamladım',
                cancelButtonText: "İptal"
            }).then((result) => {
                if (result.isConfirmed) {
                    receipt.demandId = $(this).attr("data-id");
                    $("#serviceModal").modal('toggle');
                    console.log(receipt);
                }
            });
        });

    $("#addEntry").on("click",
        () => {
            if ($("#entryList td").length == 0) {
                $("#productTable").removeClass("d-none");
            }
            var product = $(".productSelect option:selected").text();
            var productId = $(".productSelect").val();
            var price = $(".productSelect option:selected").attr("data-price");
            var quantity = $("#quantity").val();
            var list = $("#entryList");
            var exists = false;

            if (product && quantity) {


                list.children().each(function() {
                    if (productId == $(this).attr("data-id")){
                        $($(this).children()[1]).text(parseFloat($($(this).children()[1]).text()) + parseFloat(quantity));
                        $($(this).children()[3]).text(parseFloat($($(this).children()[3]).text()) + parseFloat(quantity)*parseFloat(price) + "₺" );
                        exists = true;

                        var index = receipt.products.findIndex(x => x.id == productId);
                        console.log("index",index);
                        console.log("receipt",receipt);
                        receipt.products[index].quantity += parseFloat(quantity);
                        console.log("aa",receipt);
                        return;
                        }
                });

                if (!exists) {
                    receipt.products.push({id:productId,quantity:parseFloat(quantity)});

                    var listItem = $(`<tr data-id="${productId}"><td>${product}</td><td>${quantity}</td><td>${price}₺</td><td>${parseFloat(price)*parseFloat(quantity)}₺</td><td class="row"><i style="cursor:pointer" class="fa fa-trash text-danger text-sm deleteProduct"></i></td></tr>`);

                    $("#info").text('');
                    list.append(listItem);

                    $(".deleteProduct").on("click",
                        function() {
                            Swal.fire({
                                title: 'Bu ürünü silmek istediğinize emin misiniz?',
                                icon: 'question',
                                showCancelButton: true,
                                confirmButtonColor: '#007c77',
                                cancelButtonColor: '#ffc600',
                                confirmButtonText: 'Evet',
                                cancelButtonText: "İptal"
                            }).then((result) => {
                                if (result.isConfirmed) {
                                    $(this).parent().parent().remove();
                                    receipt.products = receipt.products.filter(x => x.id != $(this).parent().parent().attr("data-id"));
                                    console.log(receipt);

                                    if($("#entryList td").length == 0) {
                                        $("#productTable").addClass("d-none");
                                        $("#info").text('Herhangi bir ürün eklenmedi.');
                                    }
                                }
                            });
                        });
                }

                $(".productSelect").val("Lütfen bir ürün seçiniz");
                $("#quantity").val("");
            }
        });

    $("#serviceModal").on("hidden.bs.modal", function () {
        $("#entryList").html("");
        $("#productTable").addClass("d-none");
        $("#info").text('Herhangi bir ürün eklenmedi.');
        receipt.products = [];
    });

    
    $("#sendProducts").on("click",
        function() {
            console.log("tıklandı");
            $.ajax({
                type: 'POST',
                data: receipt,
                url: '/Service/AcceptedDemands',
                //contentType: 'application/json',
                //dataType: 'json',
                success: () => {
                    var timerInterval;
                    Swal.fire({
                        title: 'Fatura başarıyla gönderildi!',
                        icon: "success",
                        html: 'Bu pencere <b></b> saniye içerisinde kapanacak.',
                        timer: 2000,
                        timerProgressBar: true,
                        didOpen: () => {
                            Swal.showLoading()
                            var b = Swal.getHtmlContainer().querySelector('b')
                            timerInterval = setInterval(() => {
                                    b.textContent = Swal.getTimerLeft() / 1000;
                                },
                                100);
                        },
                        willClose: () => {
                            clearInterval(timerInterval);
                        }
                    }).then(() => {
                        location.reload();
                    });
                }
            });
        });

</script>

indiGo.Web/Views/Service/CompletedDemands.cshtml
@model List<indiGo.Core.ViewModels.PageViewModels.CompletedDemandsPageViewModel>


    <div class="col-lg-8 pb-5 pl-lg-5 offset-lg-2 mt-5">
    <h3 class="pb-4">Tamamlanan İşler</h3>
    
    <div class="list-group">
        @if (Model != null)
        {
            @foreach (var demand in Model)
            {
                <a href="#" onclick="showModal(@Json.Serialize(demand).ToString())" class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1"><i class="fa fa-user"></i> @demand.ServiceDemand.FirstName @demand.ServiceDemand.LastName</h5>
                        <small>@demand.ServiceDemand.CreatedAt.ToShortDateString()</small>
                    </div>
                    @if (@demand.ServiceDemand.Category == "electric")
                    {
                        <i class="fa fa-plug text-primary"></i> <span>Elektrik Tesisatı</span>
                    }else if (@demand.ServiceDemand.Category == "gas")
                    {
                        <img src="../../fonts/CustomIcons/geyser.svg" style="margin-left: -3px" width="19px" height="19px" class=""/> <span>Doğalgaz Tesisatı</span>
                    }else if (@demand.ServiceDemand.Category == "plumbing")
                    {
                        <img src="../../fonts/CustomIcons/water.svg" style="margin-left: -3px" width="18px" height="16px"/> <span>Su Tesisatı</span>
                    }
                    <div>
                        <i class="fa fa-money-bill d-inline" style="margin-left: 2px;margin-right: 2px"></i>
                        <p class="d-inline">@demand.TotalPrice ₺</p>
                    </div>
                                
                    @if (!demand.ServiceDemand.Paid)
                    {
                        <span class="badge badge-primary badge-pill">Beklemede. Ödeme gerçekleştiğinde sizinle mail yoluyla iletişime geçilecek.</span>
                    }
                    else
                    {
                        <span class="badge badge-secondary badge-pill">Ödeme alındı. Mail yoluyla iletişime geçildi.</span>
                    }
                                
                </a>
            }
        }
    </div>
</div>


<div class="modal fade" id="serviceModal" role="dialog" aria-labelledby="serviceModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">Fatura Detayı</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body px-3">
                <div id="listContainer">
                    <h4 class="mt-3">Yapılan İşler</h4>
                    <table id="productTable" class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">Ürün</th>
                                <th scope="col">Adet</th>
                                <th scope="col">Birim Fiyat</th>
                                <th scope="col">Toplam Fiyat</th>
                            </tr>
                        </thead>
                        <tbody id="entryList">
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" data-dismiss="modal">Kapat</button>
            </div>
        </div>
    </div>
</div>


<script>
    var list = $("#entryList");
    function showModal(param) {
        list.text("");
        param.products.forEach(x => {
            var listItem = $(`<tr><td>${x.name}</td><td>${x.quantity}</td><td>${x.price}₺</td><td>${parseFloat(x.price)*parseFloat(x.quantity)}₺</td></tr>`);
            list.append(listItem);
        });
        var total = $(`<tr><td colspan='3'>Toplam Tutar</td><td>${param.totalPrice} ₺</td></tr>`);
        list.append(total);
        $("#serviceModal").modal('toggle');
    }
</script>

indiGo.Web/Views/Service/WaitingDemands.cshtml
@model List<ServiceDemandViewModel>

<div class="col-lg-8 pb-5 pl-lg-5 offset-lg-2 mt-5">
    <h3 class="pb-4">Bekleyen İşler</h3>
    <div class="list-group">
        @if (Model != null)
        {
            @if (Model.Count != 0)
            {
                @foreach (var demand in Model)
                {
                    <form asp-controller="Service" asp-action="TakeJob">
                        <input name="serviceId" type="hidden" value="@demand.Id" />
                        <button class="list-group-item list-group-item-action flex-column align-items-start servicesList">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1"><i class="fa fa-user"></i> @demand.FirstName @demand.LastName</h5>
                                <small>@demand.CreatedAt.ToShortDateString()</small>
                            </div>
                            @if (@demand.Category == "electric")
                            {
                                <i class="fa fa-plug text-primary"></i>
                                <span>Elektrik Tesisatı</span>
                            }
                            else if (@demand.Category == "gas")
                            {
                                <img src="../../fonts/CustomIcons/geyser.svg" style="margin-left: -3px" width="19px" height="19px" class=""/>
                                <span>Doğalgaz Tesisatı</span>
                            }
                            else if (@demand.Category == "plumbing")
                            {
                                <img src="../../fonts/CustomIcons/water.svg" style="margin-left: -3px" width="18px" height="16px"/>
                                <span>Su Tesisatı</span>
                            }
                            <div>
                                <i class="fa fa-exclamation d-inline" style="margin-left: 2px; margin-right: 2px"></i>
                                <p class="d-inline">@demand.Problem</p>
                            </div>
                            <div>
                                <svg class="" width="12px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M168.3 499.2C116.1 435 0 279.4 0 192C0 85.96 85.96 0 192 0C298 0 384 85.96 384 192C384 279.4 267 435 215.7 499.2C203.4 514.5 180.6 514.5 168.3 499.2H168.3zM192 256C227.3 256 256 227.3 256 192C256 156.7 227.3 128 192 128C156.7 128 128 156.7 128 192C128 227.3 156.7 256 192 256z"/></svg>
                                <span> @demand.Address.Neighborhood Mahallesi, @demand.Address.Street Sokağı/Caddesi, No:@demand.Address.ApartmentNo, Daire:@demand.Address.FlatNo, @demand.Address.District/@demand.Address.City </span>
                            </div>

                        </button>
                    </form>
                }
            }
            else
            {
                <p>Bekleyen İş Bulunmamaktadır.</p>
            }
        }

    </div>
</div>

<script>
    $(() => {
        if ("@TempData["status"]" == "success") {
            toastr.success("İş başarıyla onaylandı");
        }else if ("@TempData["status"]" == "fail") {
            toastr.error("Bir hata oluştu");
        }
    });


    $(".servicesList").on("click",
        function(e) {
            e.preventDefault();
            Swal.fire({
                title: 'Bu işi kabul etmek istediğine emin misiniz?',
                icon: 'question',
                showCancelButton: true,
                confirmButtonColor: '#007c77',
                cancelButtonColor: '#ffc600',
                confirmButtonText: 'Evet',
                cancelButtonText: "İptal"
            }).then((result) => {
                if (result.isConfirmed) {
                    $(this).parent().submit();
                }
            });;
        });

</script>