indiGo.Web/Controllers/OperatorController.cs
using System.Text;
using System.Text.Encodings.Web;
using indiGo.Business.Repositories.Abstract;
using indiGo.Core.Emails;
using indiGo.Core.Entities;
using indiGo.Core.Identity;
using indiGo.Core.Services;
using indiGo.Core.ViewModels;
using indiGo.Core.ViewModels.PageViewModels;
using indiGo.Data.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;

namespace indiGo.Web.Controllers;

[Authorize(Roles = "OPERATOR")]
public class OperatorController : Controller
{
    private readonly IRepository<ServiceDemand, int> _serviceDemandRepository;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IRepository<Address, int> _addressRepository;
    private readonly IEmailService _emailService;


    public OperatorController(IRepository<ServiceDemand, int> serviceDemandRepository, UserManager<ApplicationUser> userManager, IRepository<Address, int> addressRepository, IEmailService emailService)
    {
        _serviceDemandRepository = serviceDemandRepository;
        _userManager = userManager;
        _addressRepository = addressRepository;
        _emailService = emailService;
    }

    [HttpGet]
    public async Task<IActionResult> ServiceDemands()
    {
        var model = new AdminWaitingDemandsPageViewModel();

        var electricalTechnicsA = await _userManager.GetUsersInRoleAsync(Roles.ElectricalService);
        var gasTechnicsA = await _userManager.GetUsersInRoleAsync(Roles.GasService);
        var plumbingTechnicsA = await _userManager.GetUsersInRoleAsync(Roles.PlumbingService);

        var electricalTechnics = new List<ApplicationUser>(electricalTechnicsA);
        var gasTechnics = new List<ApplicationUser>(gasTechnicsA);
        var plumbingTechnics = new List<ApplicationUser>(plumbingTechnicsA);


        var serviceDemands = _serviceDemandRepository.Get().ToList();
        serviceDemands.ForEach(x =>
        {
            if (x.ServiceId != null)
            {
                return;
            }
            var address = _addressRepository.GetById(x.AddressId);
            model.ServiceDemands.Add(new ServiceDemandViewModel()
            {
                Id = x.Id,
                AddressId = x.AddressId,
                FirstName = x.FirstName,
                LastName = x.LastName,
                PhoneNumber = x.PhoneNumber,
                Problem = x.Problem,
                TCKN = x.TCKN,
                Category = x.Category,
                Address = address
            });
        });

        electricalTechnics.ForEach(x =>
        {
            model.ElectricalTechnics.Add(new UserViewModel()
            {
                Email = x.Email,
                FirstName = x.FirstName,
                LastName = x.LastName,
                PhoneNumber = x.PhoneNumber,
                RegisterDate = x.RegisterDate,
                Id = x.Id
            });
        });


        gasTechnics.ForEach(x =>
        {
            model.GasTechnics.Add(new UserViewModel()
            {
                Email = x.Email,
                FirstName = x.FirstName,
                LastName = x.LastName,
                PhoneNumber = x.PhoneNumber,
                RegisterDate = x.RegisterDate,
                Id = x.Id
            });
        });

        plumbingTechnics.ForEach(x =>
        {
            model.PlumbingTechnics.Add(new UserViewModel()
            {
                Email = x.Email,
                FirstName = x.FirstName,
                LastName = x.LastName,
                PhoneNumber = x.PhoneNumber,
                RegisterDate = x.RegisterDate,
                Id = x.Id
            });
        });

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> ServiceDemands(int demandId, string serviceId)
    {
        var user = await _userManager.FindByIdAsync(serviceId);
        var demand = _serviceDemandRepository.GetById(demandId);
        if (user == null || demand == null)
        {
            return View();
        }
        demand.ServiceId = serviceId;
        _serviceDemandRepository.Save();



        var emailMessage = new MailModel()
        {
            To = new List<EmailModel>
            {
                new EmailModel
                {
                    Email = user.Email,
                    Name = user.FirstName
                }
            },
            Body = $"Servis talebiniz onaylanmıştır. En kısa zamanda sizinle iletişime geçilecektir. İyi günler.",
            Subject = "Servis Talebi Onaylandı"
        };
        await _emailService.SendEmailAsync(emailMessage);



        TempData["status"] = "success";
        return RedirectToAction("ServiceDemands");
    }

    [HttpGet]
    public async Task<IActionResult> AssignedDemands()
    {
        var model = new AdminWaitingDemandsPageViewModel();

        var electricalTechnicsA = await _userManager.GetUsersInRoleAsync(Roles.ElectricalService);
        var gasTechnicsA = await _userManager.GetUsersInRoleAsync(Roles.GasService);
        var plumbingTechnicsA = await _userManager.GetUsersInRoleAsync(Roles.PlumbingService);

        var electricalTechnics = new List<ApplicationUser>(electricalTechnicsA);
        var gasTechnics = new List<ApplicationUser>(gasTechnicsA);
        var plumbingTechnics = new List<ApplicationUser>(plumbingTechnicsA);


        var serviceDemands = _serviceDemandRepository.Get().ToList();
        serviceDemands.ForEach(async x =>
        {
            if (x.ServiceId == null)
            {
                return;
            }
            var address = _addressRepository.GetById(x.AddressId);
            var service = await _userManager.FindByIdAsync(x.ServiceId);
            model.ServiceDemands.Add(new ServiceDemandViewModel()
            {
                Id = x.Id,
                AddressId = x.AddressId,
                FirstName = x.FirstName,
                LastName = x.LastName,
                PhoneNumber = x.PhoneNumber,
                Problem = x.Problem,
                TCKN = x.TCKN,
                Category = x.Category,
                Address = address,
                Service = new UserViewModel()
                {
                    FirstName = service.FirstName,
                    LastName = service.LastName,
                    Id = service.Id,
                    Email = service.Email,
                    PhoneNumber = service.PhoneNumber,
                    RegisterDate = service.RegisterDate
                }
            });
        });

        electricalTechnics.ForEach(x =>
        {
            model.ElectricalTechnics.Add(new UserViewModel()
            {
                Email = x.Email,
                FirstName = x.FirstName,
                LastName = x.LastName,
                PhoneNumber = x.PhoneNumber,
                RegisterDate = x.RegisterDate,
                Id = x.Id
            });
        });


        gasTechnics.ForEach(x =>
        {
            model.GasTechnics.Add(new UserViewModel()
            {
                Email = x.Email,
                FirstName = x.FirstName,
                LastName = x.LastName,
                PhoneNumber = x.PhoneNumber,
                RegisterDate = x.RegisterDate,
                Id = x.Id
            });
        });

        plumbingTechnics.ForEach(x =>
        {
            model.PlumbingTechnics.Add(new UserViewModel()
            {
                Email = x.Email,
                FirstName = x.FirstName,
                LastName = x.LastName,
                PhoneNumber = x.PhoneNumber,
                RegisterDate = x.RegisterDate,
                Id = x.Id
            });
        });

        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Services()
    {
        var electicalServices = new List<ApplicationUser>(await _userManager.GetUsersInRoleAsync(Roles.ElectricalService));
        var gasServices = new List<ApplicationUser>(await _userManager.GetUsersInRoleAsync(Roles.GasService));
        var plumbingServices = new List<ApplicationUser>(await _userManager.GetUsersInRoleAsync(Roles.PlumbingService));

        var model = new ServicesViewModel();

        electicalServices.ForEach(x =>
        {
            model.ElectricalServices.Add(new UserViewModel()
            {
                Id = x.Id,
                FirstName = x.FirstName,
                LastName = x.LastName,
                Email = x.Email,
                PhoneNumber = x.PhoneNumber,
                RegisterDate = x.RegisterDate
            });
        });
        gasServices.ForEach(x =>
        {
            model.GasServices.Add(new UserViewModel()
            {
                Id = x.Id,
                FirstName = x.FirstName,
                LastName = x.LastName,
                Email = x.Email,
                PhoneNumber = x.PhoneNumber,
                RegisterDate = x.RegisterDate
            });
        });
        plumbingServices.ForEach(x =>
        {
            model.PlumbingServices.Add(new UserViewModel()
            {
                Id = x.Id,
                FirstName = x.FirstName,
                LastName = x.LastName,
                PhoneNumber = x.PhoneNumber,
                RegisterDate = x.RegisterDate,
                Email = x.Email
            });
        });


        return View(model);
    }
}

indiGo.Web/Controllers/ServiceController.cs
using indiGo.Business.Repositories.Abstract;
using indiGo.Core.Entities;
using indiGo.Core.Identity;
using indiGo.Core.ViewModels;
using indiGo.Core.ViewModels.PageViewModels;
using indiGo.Data.Identity;
using indiGo.Web.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace indiGo.Web.Controllers;

[Authorize(Roles = "ELECTRICALSERVICE,GASSERVICE,PLUMBINGSERVICE")]
public class ServiceController : Controller
{
    private readonly IRepository<ServiceDemand, int> _serviceDemandRepository;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IRepository<Address, int> _addressRepository;
    private readonly IRepository<Product,int> _productRepository;
    private readonly IRepository<Receipt,int> _receiptRepository;
    private readonly IRepository<ReceiptDetail,int> _receiptDetailRepository;

    public ServiceController(IRepository<ServiceDemand, int> serviceDemandRepository, UserManager<ApplicationUser> userManager, IRepository<Address, int> addressRepository, IRepository<Product, int> productRepository, IRepository<Receipt, int> receiptRepository, IRepository<ReceiptDetail, int> receiptDetailRepository)
    {
        _serviceDemandRepository = serviceDemandRepository;
        _userManager = userManager;
        _addressRepository = addressRepository;
        _productRepository = productRepository;
        _receiptRepository = receiptRepository;
        _receiptDetailRepository = receiptDetailRepository;
    }

    [HttpGet]
    public IActionResult WaitingDemands()
    {
        var demands = _serviceDemandRepository.Get(x => x.ServiceId == HttpContext.GetUserId()).ToList();

        var model = new List<ServiceDemandViewModel>();
        demands.ForEach(x =>
        {
            if (x.Accepted)
            {
                return;
            }
            var address = _addressRepository.GetById(x.AddressId);
            model.Add(new ServiceDemandViewModel()
            {
                Id = x.Id,
                FirstName = x.FirstName,
                LastName = x.LastName,
                Address = address,
                AddressId = x.AddressId,
                Category = x.Category,
                CreatedAt = x.CreatedAt,
                PhoneNumber = x.PhoneNumber,
                TCKN = x.TCKN,
                Problem = x.Problem
            });
        });

        return View(model);
    }

    [HttpPost]
    public IActionResult TakeJob(int serviceId)
    {
        var demand = _serviceDemandRepository.GetById(serviceId);
        if (demand == null)
        {
            TempData["status"] = "fail";
        }
        else
        {
            demand.Accepted = true;
            _serviceDemandRepository.Save();
            TempData["status"] = "success";
        }
        return RedirectToAction("WaitingDemands");
    }

    [HttpGet]
    public IActionResult AcceptedDemands()
    {
        var demands = _serviceDemandRepository.Get(x => x.ServiceId == HttpContext.GetUserId() && !x.Receipted).ToList();
        var products = _productRepository.Get().ToList();

        var model = new AcceptedDemandsPageViewModel();
        
        demands.ForEach(x =>
        {
            if (!x.Accepted)
            {
                return;
            }
            var address = _addressRepository.GetById(x.AddressId);
            model.ServiceDemands.Add(new ServiceDemandViewModel()
            {
                Id = x.Id,
                FirstName = x.FirstName,
                LastName = x.LastName,
                Address = address,
                AddressId = x.AddressId,
                Category = x.Category,
                CreatedAt = x.CreatedAt,
                PhoneNumber = x.PhoneNumber,
                TCKN = x.TCKN,
                Problem = x.Problem
            });
        });

        products.ForEach(x =>
        {
            model.Products.Add(new ProductViewModel()
            {
                Id = x.Id,
                Category = x.Category,
                Name = x.Name,
                Price = x.Price
            });
        });

        return View(model);
    }

    [HttpPost]
    public IActionResult AcceptedDemands(DemandProductReceiptViewModel model)
    {
        var demand = _serviceDemandRepository.GetById(model.DemandId);
        var receipt = new Receipt()
        {
            DemandId = model.DemandId
        };

        _receiptRepository.Insert(receipt);
        _receiptRepository.Save();

        model.Products.ForEach(x =>
        {
            _receiptDetailRepository.Insert(new ReceiptDetail()
            {
                ProductId = x.Id, 
                ReceiptId = receipt.Id,
                Quantity = x.Quantity
            });
        });
        demand.Receipted = true;
        _receiptDetailRepository.Save();
        _serviceDemandRepository.Save();

        TempData["ReceiptCreated"] = "success";
        
        return RedirectToAction("AcceptedDemands");
    }

    [HttpGet]
    public IActionResult CompletedDemands()
    {
        var demands = _serviceDemandRepository.Get(x => x.ServiceId == HttpContext.GetUserId() && x.Receipted).ToList();
        
        var model = new List<CompletedDemandsPageViewModel>();

        demands.ForEach(x =>
        {
            var receipt = _receiptRepository.Get(y => y.DemandId == x.Id).FirstOrDefault();
            var details = _receiptDetailRepository.Get(y => y.ReceiptId == receipt.Id).ToList();
            model.Add(new CompletedDemandsPageViewModel()
            {
                ServiceDemand = new ServiceDemandViewModel()
                {
                    FirstName = x.FirstName,
                    LastName = x.LastName,
                    AddressId = x.AddressId,
                    Accepted = x.Accepted,
                    Category = x.Category,
                    Completed = x.Completed,
                    CreatedAt = x.CreatedAt,
                    Id = x.Id,
                    PhoneNumber = x.PhoneNumber,
                    Paid = x.Paid,
                    Problem = x.Problem,
                    ServiceId = x.ServiceId,
                    Receipted = x.Receipted,
                    TCKN = x.TCKN
                },
            });
            details.ForEach(y =>
            {
                var product = _productRepository.GetById(y.ProductId);
                model.Last().Products.Add(new ReceiptProductViewModel()
                {
                    Id = product.Id,
                    Price = product.Price,
                    Category = product.Category,
                    Name = product.Name,
                    Quantity = y.Quantity
                });
                model.Last().TotalPrice += Math.Round(y.Quantity * product.Price,2);
            });
            

        });

      
        return View(model);
    }

}

indiGo.Web/Views/Operator/AssignedDemands.cshtml
@model indiGo.Core.ViewModels.PageViewModels.AdminWaitingDemandsPageViewModel

<div class="col-lg-8 pb-5 pl-lg-5 offset-lg-2 mt-5">
    <h3 class="pb-4">Atanan İşler</h3>
    <div class="list-group">
        @if (Model != null)
        {
            @if (Model.ServiceDemands.Count != 0)
            {
                @foreach (var demand in Model.ServiceDemands)
                {
                    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start servicesList">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1"><i class="fa fa-user"></i> @demand.FirstName @demand.LastName</h5>
                            <small>@demand.CreatedAt.ToShortDateString()</small>
                        </div>
                        @if (@demand.Category == "electric")
                        {
                            <i class="fa fa-plug text-primary"></i> <span>Elektrik Tesisatı</span>
                        }
                        else if (@demand.Category == "gas")
                        {
                            <img src="../../fonts/CustomIcons/geyser.svg" style="margin-left: -3px" width="19px" height="19px" class="" /> <span>Doğalgaz Tesisatı</span>
                        }
                        else if (@demand.Category == "plumbing")
                        {
                            <img src="../../fonts/CustomIcons/water.svg" style="margin-left: -3px" width="18px" height="16px" /> <span>Su Tesisatı</span>
                        }
                        <div>
                            <i class="fa fa-exclamation d-inline" style="margin-left: 2px;margin-right: 2px"></i>
                            <p class="d-inline">@demand.Problem</p>
                        </div>
                        <div>
                            <svg class="" width="12px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M168.3 499.2C116.1 435 0 279.4 0 192C0 85.96 85.96 0 192 0C298 0 384 85.96 384 192C384 279.4 267 435 215.7 499.2C203.4 514.5 180.6 514.5 168.3 499.2H168.3zM192 256C227.3 256 256 227.3 256 192C256 156.7 227.3 128 192 128C156.7 128 128 156.7 128 192C128 227.3 156.7 256 192 256z" /></svg>
                            <span> @demand.Address.Neighborhood Mahallesi, @demand.Address.Street Sokağı/Caddesi, No:@demand.Address.ApartmentNo, Daire:@demand.Address.FlatNo, @demand.Address.District/@demand.Address.City </span>
                        </div>
                        <div>
                            <span class="badge badge-secondary badge-pill">@demand.Service.FirstName @demand.Service.LastName Servisine Atandı.</span>
                        </div>
                        @if (demand.Receipted)
                        {
                            <div>
                                <span class="badge badge-primary badge-pill">İş Tamamlandı.</span>
                            </div>
                        }
                        else
                        {
                            <div>
                                <span class="badge badge-primary badge-pill">Tamamlanması bekleniyor.</span>
                            </div>
                        }
                        

                    </a>
                }
            }
            else
            {
                <p>Onaylanan Talep Bulunmamaktadır.</p>
            }
        }
    </div>
</div>

indiGo.Web/Views/Operator/ServiceDemands.cshtml
@model indiGo.Core.ViewModels.PageViewModels.AdminWaitingDemandsPageViewModel

<div class="col-lg-8 pb-5 pl-lg-5 offset-lg-2 mt-5">
    <h3 class="pb-4">Servis Taleplerim</h3>
    <div class="list-group">
        @if (Model != null)
        {
            @if (Model.ServiceDemands.Count != 0)
            {
                @foreach (var demand in Model.ServiceDemands)
                {
                    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start servicesList" onclick="showModal({id:'@demand.Id',firstName:'@demand.FirstName', lastName: '@demand.LastName', category: '@demand.Category', problem: '@demand.Problem', date: '@demand.CreatedAt.ToShortDateString()', neighborhood: '@demand.Address.Neighborhood', street:'@demand.Address.Street', apartmentNo:'@demand.Address.ApartmentNo', flatNo:'@demand.Address.FlatNo', district:'@demand.Address.District', city: '@demand.Address.City' })">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1"><i class="fa fa-user"></i> @demand.FirstName @demand.LastName</h5>
                            <small>@demand.CreatedAt.ToShortDateString()</small>
                        </div>
                        @if (@demand.Category == "electric")
                        {
                            <i class="fa fa-plug text-primary"></i> <span>Elektrik Tesisatı</span>
                        }
                        else if (@demand.Category == "gas")
                        {
                            <img src="../../fonts/CustomIcons/geyser.svg" style="margin-left: -3px" width="19px" height="19px" class="" /> <span>Doğalgaz Tesisatı</span>
                        }
                        else if (@demand.Category == "plumbing")
                        {
                            <img src="../../fonts/CustomIcons/water.svg" style="margin-left: -3px" width="18px" height="16px" /> <span>Su Tesisatı</span>
                        }
                        <div>
                            <i class="fa fa-exclamation d-inline" style="margin-left: 2px;margin-right: 2px"></i>
                            <p class="d-inline">@demand.Problem</p>
                        </div>
                        <div>
                            <svg class="" width="12px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M168.3 499.2C116.1 435 0 279.4 0 192C0 85.96 85.96 0 192 0C298 0 384 85.96 384 192C384 279.4 267 435 215.7 499.2C203.4 514.5 180.6 514.5 168.3 499.2H168.3zM192 256C227.3 256 256 227.3 256 192C256 156.7 227.3 128 192 128C156.7 128 128 156.7 128 192C128 227.3 156.7 256 192 256z" /></svg>
                            <span> @demand.Address.Neighborhood Mahallesi, @demand.Address.Street Sokağı/Caddesi, No:@demand.Address.ApartmentNo, Daire:@demand.Address.FlatNo, @demand.Address.District/@demand.Address.City </span>
                        </div>

                    </a>
                }
            }
            else
            {
                <p>Onaylanmayan Talep Bulunmamaktadır.</p>
            }
        }

    </div>
</div>


<div class="modal fade" id="serviceModal" role="dialog" aria-labelledby="serviceModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">Teknik Servis Talep Atama</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="" id="editAddressForm" asp-controller="Operator" asp-action="ServiceDemands">
                <input id="demandId" name="demandId" type="hidden" />
                <div class="modal-body">
                    <div>
                        <div class="d-flex w-100 justify-content-between" id="namePart">
                            <h5 id="demandName" class="mb-1"></h5>
                            <small id="datePart"></small>
                        </div>
                    </div>
                    <div id="info">
                    </div>
                    <div class="form-row">
                        <div id="dropdownPart" class="form-group col-md-6">
                            <label class="mt-5">Atanacak Teknik Servis</label>

                        </div>
                        <div id="otherInfo">
                        </div>

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">İptal</button>
                    <button type="submit" class="btn btn-secondary">Servis Ata</button>
                </div>
            </form>
            <select name="serviceId" id="electricalDropdown" class="custom-select d-none">
                <option>Teknik Servis Seçiniz.</option>
                @foreach (var item in Model.ElectricalTechnics)
                {
                    <option value="@item.Id">@item.FirstName @item.LastName</option>
                }
            </select>
            <select name="serviceId" id="gasDropdown" class="custom-select d-none">
                <option>Teknik Servis Seçiniz.</option>
                @foreach (var item in Model.GasTechnics)
                {
                    <option value="@item.Id">@item.FirstName @item.LastName</option>
                }
            </select>
            <select name="serviceId" id="plumbingDropdown" class="custom-select d-none">
                <option>Teknik Servis Seçiniz.</option>
                @foreach (var item in Model.PlumbingTechnics)
                {
                    <option value="@item.Id">@item.FirstName @item.LastName</option>
                }
            </select>
        </div>
    </div>
</div>


<script>
    $(() => {
        if ("@TempData["status"]" == "success") {
            toastr.success("Atama işlemi başarılı");
        }
    });

    $('#serviceModal').on('hidden.bs.modal', function (e) {
        $('#info').empty();
        $("#electricalDropdown").addClass("d-none").appendTo($(".modal-content"));
        $("#gasDropdown").addClass("d-none").appendTo($(".modal-content"));
        $("#plumbingDropdown").addClass("d-none").appendTo($(".modal-content"));
    })
    function showModal(parameter) {
        if ($('#serviceModal').hasClass('show')) {
            $('#serviceModal').modal('hide');
        } else {
            $("#demandName").html(`<i class='fa fa-user'></i> ${parameter.firstName} ${parameter.lastName}`);
            $("#datePart").html(parameter.date);
            var icon;
            var text;
            if (parameter.category == "electric") {
                icon = $('<i class="fa fa-plug text-primary"></i>');
                text = $('<span>Elektrik Tesisatı</span>');
                $("#electricalDropdown").appendTo($("#dropdownPart")).removeClass("d-none");
            }else if (parameter.category == "gas") {
                icon = $('<img src="../../fonts/CustomIcons/geyser.svg" style="margin-left: -3px" width="19px" height="19px" class="" />');
                text = $('<span>Doğalgaz Tesisatı</span>');
                $("#gasDropdown").appendTo($("#dropdownPart")).removeClass("d-none");
            }else if (parameter.category == "plumbing") {
                icon =  $('<img src="../../fonts/CustomIcons/water.svg" style="margin-left: -3px" width="18px" height="16px" />');
                text = $('<span>Su Tesisatı</span>');
                $("#plumbingDropdown").appendTo($("#dropdownPart")).removeClass("d-none");
            }
            var problem = $(`<i class="fa fa-exclamation d-inline" style="margin-left: 2px;margin-right: 2px"></i> <p class="d-inline">${parameter.problem}</p>`);
            var address = $(`<svg class="" width="12px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path d="M168.3 499.2C116.1 435 0 279.4 0 192C0 85.96 85.96 0 192 0C298 0 384 85.96 384 192C384 279.4 267 435 215.7 499.2C203.4 514.5 180.6 514.5 168.3 499.2H168.3zM192 256C227.3 256 256 227.3 256 192C256 156.7 227.3 128 192 128C156.7 128 128 156.7 128 192C128 227.3 156.7 256 192 256z" /></svg>
                        <span> ${parameter.neighborhood}, ${parameter.street} Sokağı/Caddesi, No:${parameter.apartmentNo}, Daire:${parameter.flatNo}, ${parameter.district}/${parameter.city} </span>`);
            $("#info").append(icon).append(text).append($('<div>').append(problem)).append($('<div>').append(address));
            $("#demandId").val(parameter.id);

            $('#serviceModal').modal('show');
        }
    }
</script>