indiGo.Web/Controllers/ServiceDemandController.cs
using indiGo.Business.Repositories.Abstract;
using indiGo.Core.Categories;
using indiGo.Core.Entities;
using indiGo.Core.ViewModels;
using indiGo.Data.Identity;
using indiGo.Web.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace indiGo.Web.Controllers;

public class ServiceDemandController : Controller
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IRepository<Address,int> _addressRepository;
    private readonly IRepository<ServiceDemand, int> _serviceDemandRepository;

    public ServiceDemandController(IRepository<Address, int> addressRepository, UserManager<ApplicationUser> userManager, IRepository<ServiceDemand, int> serviceDemandRepository)
    {
        _addressRepository = addressRepository;
        _userManager = userManager;
        _serviceDemandRepository = serviceDemandRepository;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public IActionResult ElectricalServiceDemand()
    {
        var userId = HttpContext.GetUserId();
        var addresses = _addressRepository.Get(x=>x.UserId == userId).ToList();
       
        var model = new ServiceDemandPageViewModel();

        addresses.ForEach(x =>
        {
            model.Addresses.Add(new SelectListItem()
            {
                Value = x.Id.ToString(),
                Text = x.AddressName

            });
        });

        return View(model);
    }

    [HttpPost]
    public IActionResult ElectricalServiceDemand(ServiceDemandPageViewModel model)
    {
        var userId = HttpContext.GetUserId();
        var adresses = _addressRepository.Get(x => x.UserId == userId).ToList();

        adresses.ForEach(x =>
        {
            model.Addresses.Add(new SelectListItem()
            {
                Value = x.Id.ToString(),
                Text = x.AddressName
            });
        });

        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var serviceDemand = new ServiceDemand()
        {
            FirstName = model.ServiceDemand.FirstName,
            LastName = model.ServiceDemand.LastName,
            PhoneNumber = model.ServiceDemand.PhoneNumber,
            Problem = model.ServiceDemand.Problem,
            TCKN = model.ServiceDemand.TCKN,
            AddressId = model.ServiceDemand.AddressId,
            Category = Categories.Electric,
            UserId = userId
        };

        _serviceDemandRepository.Insert(serviceDemand);
        _serviceDemandRepository.Save();

        TempData["status"] = "success";
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult GasServiceDemand()
    {
        var userId = HttpContext.GetUserId();
        var adresses = _addressRepository.Get(x => x.UserId == userId).ToList();
        var model = new ServiceDemandPageViewModel();

        adresses.ForEach(x =>
        {
            model.Addresses.Add(new SelectListItem()
            {
                Value = x.Id.ToString(),
                Text = x.AddressName

            });
        });

        return View(model);
    }

    [HttpPost]
    public IActionResult GasServiceDemand(ServiceDemandPageViewModel model)
    {
        var userId = HttpContext.GetUserId();
        var adresses = _addressRepository.Get(x => x.UserId == userId).ToList();

        adresses.ForEach(x =>
        {
            model.Addresses.Add(new SelectListItem()
            {
                Value = x.Id.ToString(),
                Text = x.AddressName
            });
        });

        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var serviceDemand = new ServiceDemand()
        {
            FirstName = model.ServiceDemand.FirstName,
            LastName = model.ServiceDemand.LastName,
            PhoneNumber = model.ServiceDemand.PhoneNumber,
            Problem = model.ServiceDemand.Problem,
            TCKN = model.ServiceDemand.TCKN,
            AddressId = model.ServiceDemand.AddressId,
            Category = Categories.Gas,
            UserId = userId
        };

        _serviceDemandRepository.Insert(serviceDemand);
        _serviceDemandRepository.Save();

        TempData["status"] = "success";
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult PlumbingServiceDemand()
    {
        var userId = HttpContext.GetUserId();
        var adresses = _addressRepository.Get(x => x.UserId == userId).ToList();
        var model = new ServiceDemandPageViewModel();

        adresses.ForEach(x =>
        {
            model.Addresses.Add(new SelectListItem()
            {
                Value = x.Id.ToString(),
                Text = x.AddressName

            });
        });

        return View(model);
    }

    [HttpPost]
    public IActionResult PlumbingServiceDemand(ServiceDemandPageViewModel model)
    {
        var userId = HttpContext.GetUserId();
        var adresses = _addressRepository.Get(x => x.UserId == userId).ToList();

        adresses.ForEach(x =>
        {
            model.Addresses.Add(new SelectListItem()
            {
                Value = x.Id.ToString(),
                Text = x.AddressName
            });
        });

        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var serviceDemand = new ServiceDemand()
        {
            FirstName = model.ServiceDemand.FirstName,
            LastName = model.ServiceDemand.LastName,
            PhoneNumber = model.ServiceDemand.PhoneNumber,
            Problem = model.ServiceDemand.Problem,
            TCKN = model.ServiceDemand.TCKN,
            AddressId = model.ServiceDemand.AddressId,
            Category = Categories.Plumbing,
            UserId = userId
        };

        _serviceDemandRepository.Insert(serviceDemand);
        _serviceDemandRepository.Save();

        TempData["status"] = "success";
        return RedirectToAction("Index");
    }
}

indiGo.Web/Views/ServiceDemand/ElectricalServiceDemand.cshtml
@model ServiceDemandPageViewModel

<div class="container my-5" style="min-height: 52vh">
    <div class="">
        <h6 class="text-secondary font-weight-semi-bold text-uppercase mb-3">Talep Oluştur</h6>
        <h1 class="mb-4 section-title section-title">Elektrik Tesisatı Servis Talebi</h1>
    </div>
    <form class="form-group" asp-controller="ServiceDemand" asp-action="ElectricalServiceDemand">
        <div class="modal-body">
            <div class="form-row mb-2">
                <div class="form-group col-md-6">
                    <label asp-for="ServiceDemand.FirstName"></label>
                    <input asp-for="ServiceDemand.FirstName" class="form-control" required>
                    <span asp-validation-for="ServiceDemand.FirstName" class="text-danger text-sm"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="ServiceDemand.LastName"></label>
                    <input asp-for="ServiceDemand.LastName" class="form-control" required>
                    <span asp-validation-for="ServiceDemand.LastName" class="text-danger text-sm"></span>
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group col-md-6">
                    <label asp-for="ServiceDemand.TCKN"></label>
                    <input asp-for="ServiceDemand.TCKN" class="form-control" required>
                    <span asp-validation-for="ServiceDemand.TCKN" class="text-danger text-sm"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="ServiceDemand.AddressId"></label>
                    <select class="custom-select" asp-for="ServiceDemand.AddressId" asp-items="@Model.Addresses">
                        <option>Adres seçiniz.</option>
                    </select>
                    <span asp-validation-for="ServiceDemand.AddressId" class="text-danger text-sm"></span>
                    <span class="small">Yeni adres eklemek için <a asp-controller="Account" asp-action="Addresses" class="text-primary" style="cursor: pointer">buraya tıklayabilirsiniz.</a></span>
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group col-md-6">
                    <label asp-for="ServiceDemand.Problem"></label>
                    <input asp-for="ServiceDemand.Problem" class="form-control" required>
                    <span asp-validation-for="ServiceDemand.Problem" class="text-danger text-sm"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="ServiceDemand.PhoneNumber"></label>
                    <input asp-for="ServiceDemand.PhoneNumber" class="form-control">
                    <span asp-validation-for="ServiceDemand.PhoneNumber" class="text-danger text-sm"></span>
                </div>
            </div>


        </div>
        <div class="float-right">
            <button type="submit" class="btn btn-secondary">Talep Oluştur</button>
        </div>
    </form>
</div>

indiGo.Web/Views/ServiceDemand/GasServiceDemand.cshtml
@model ServiceDemandPageViewModel

<div class="container my-5" style="min-height: 52vh">
    <div class="">
        <h6 class="text-secondary font-weight-semi-bold text-uppercase mb-3">Talep Oluştur</h6>
        <h1 class="mb-4 section-title section-title">Doğazgaz Tesisatı Servis Talebi</h1>
    </div>
    <form class="form-group" asp-controller="ServiceDemand" asp-action="GasServiceDemand">
        <div class="modal-body">
            <div class="form-row mb-2">
                <div class="form-group col-md-6">
                    <label asp-for="ServiceDemand.FirstName"></label>
                    <input asp-for="ServiceDemand.FirstName" class="form-control" required>
                    <span asp-validation-for="ServiceDemand.FirstName" class="text-danger text-sm"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="ServiceDemand.LastName"></label>
                    <input asp-for="ServiceDemand.LastName" class="form-control" required>
                    <span asp-validation-for="ServiceDemand.LastName" class="text-danger text-sm"></span>
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group col-md-6">
                    <label asp-for="ServiceDemand.TCKN"></label>
                    <input asp-for="ServiceDemand.TCKN" class="form-control" required>
                    <span asp-validation-for="ServiceDemand.TCKN" class="text-danger text-sm"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="ServiceDemand.AddressId"></label>
                    <select class="custom-select" asp-for="ServiceDemand.AddressId" asp-items="@Model.Addresses">
                        <option>Adres seçiniz.</option>
                    </select>
                    <span asp-validation-for="ServiceDemand.AddressId" class="text-danger text-sm"></span>
                    <span class="small">Yeni adres eklemek için <a asp-controller="Account" asp-action="Addresses" class="text-primary" style="cursor: pointer">buraya tıklayabilirsiniz.</a></span>
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group col-md-6">
                    <label asp-for="ServiceDemand.Problem"></label>
                    <input asp-for="ServiceDemand.Problem" class="form-control" required>
                    <span asp-validation-for="ServiceDemand.Problem" class="text-danger text-sm"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="ServiceDemand.PhoneNumber"></label>
                    <input asp-for="ServiceDemand.PhoneNumber" class="form-control">
                    <span asp-validation-for="ServiceDemand.PhoneNumber" class="text-danger text-sm"></span>
                </div>
            </div>


        </div>
        <div class="float-right">
            <button type="submit" class="btn btn-secondary">Talep Oluştur</button>
        </div>
    </form>
</div>

indiGo.Web/Views/ServiceDemand/Index.cshtml
<div class="container pt-5">
    <div class="row align-items-end ">
        <div class="col-lg-6">
            <h6 class="text-secondary font-weight-semi-bold text-uppercase mb-3">Servis Talebi Oluştur</h6>
            <h1 class="section-title mb-3">Hangi alanda servise ihtiyacınız var?</h1>
        </div>
    </div>
    <div class="mb-4 text-secondary font-weight-bold">* Talep oluşturabilmek için profil sayfasından adres eklemiş olmanız gerekmektedir.</div>
    <div class="row m-0 portfolio-container pb-5">
        <div class="col-lg-4 col-md-6 col-sm-12 px-2 portfolio-item first">
            <div class="position-relative overflow-hidden">
                <div class="portfolio-img">
                    <img class="../../img-fluid w-100" src="../../img/elektrik.jpg" height="240px" alt="">
                </div>
                <div class="portfolio-text bg-primary">
                    <h4 class="font-weight-bold mb-4">Elektrik Tesisat Servisi</h4>
                    <div class="d-flex align-items-center justify-content-center">
                        <a class="btn btn-sm btn-secondary m-1" asp-controller="ServiceDemand" asp-action="ElectricalServiceDemand">
                            Talep Oluştur
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-6 col-sm-12 px-2 portfolio-item second">
            <div class="position-relative overflow-hidden">
                <div class="portfolio-img">
                    <img class="../../img-fluid w-100" src="../../img/dogalgaz.jpg" height="240px" alt="">
                </div>
                <div class="portfolio-text bg-primary">
                    <h4 class="font-weight-bold mb-4">Doğalgaz Tesisat Servisi</h4>
                    <div class="d-flex align-items-center justify-content-center">
                        <a class="btn btn-sm btn-secondary m-1" asp-controller="ServiceDemand" asp-action="GasServiceDemand">
                            Talep Oluştur
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-6 col-sm-12 px-2 pb-5 portfolio-item third">
            <div class="position-relative overflow-hidden">
                <div class="portfolio-img">
                    <img class="../../img-fluid w-100" src="../../img/su.jpg" height="240px" alt="">
                </div>
                <div class="portfolio-text bg-primary">
                    <h4 class="font-weight-bold mb-4">Su Tesisat Servisi</h4>
                    <div class="d-flex align-items-center justify-content-center">
                        <a class="btn btn-sm btn-secondary m-1" asp-controller="ServiceDemand" asp-action="PlumbingServiceDemand">
                            Talep Oluştur
                        </a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<script>
    if ("@TempData["status"]" == "success") {
        toastr.success("Talep Başarıyla oluşturuldu.");
    }
</script>

indiGo.Web/Views/ServiceDemand/PlumbingServiceDemand.cshtml
@model ServiceDemandPageViewModel

<div class="container my-5" style="min-height: 52vh">
    <div class="">
        <h6 class="text-secondary font-weight-semi-bold text-uppercase mb-3">Talep Oluştur</h6>
        <h1 class="mb-4 section-title section-title">Su Tesisatı Servis Talebi</h1>
    </div>
    <form class="form-group" asp-controller="ServiceDemand" asp-action="PlumbingServiceDemand">
        <div class="modal-body">
            <div class="form-row mb-2">
                <div class="form-group col-md-6">
                    <label asp-for="ServiceDemand.FirstName"></label>
                    <input asp-for="ServiceDemand.FirstName" class="form-control" required>
                    <span asp-validation-for="ServiceDemand.FirstName" class="text-danger text-sm"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="ServiceDemand.LastName"></label>
                    <input asp-for="ServiceDemand.LastName" class="form-control" required>
                    <span asp-validation-for="ServiceDemand.LastName" class="text-danger text-sm"></span>
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group col-md-6">
                    <label asp-for="ServiceDemand.TCKN"></label>
                    <input asp-for="ServiceDemand.TCKN" class="form-control" required>
                    <span asp-validation-for="ServiceDemand.TCKN" class="text-danger text-sm"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="ServiceDemand.AddressId"></label>
                    <select class="custom-select" asp-for="ServiceDemand.AddressId" asp-items="@Model.Addresses">
                        <option>Adres seçiniz.</option>
                    </select>
                    <span asp-validation-for="ServiceDemand.AddressId" class="text-danger text-sm"></span>
                    <span class="small">Yeni adres eklemek için <a asp-controller="Account" asp-action="Addresses" class="text-primary" style="cursor: pointer">buraya tıklayabilirsiniz.</a></span>
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group col-md-6">
                    <label asp-for="ServiceDemand.Problem"></label>
                    <input asp-for="ServiceDemand.Problem" class="form-control" required>
                    <span asp-validation-for="ServiceDemand.Problem" class="text-danger text-sm"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="ServiceDemand.PhoneNumber"></label>
                    <input asp-for="ServiceDemand.PhoneNumber" class="form-control">
                    <span asp-validation-for="ServiceDemand.PhoneNumber" class="text-danger text-sm"></span>
                </div>
            </div>


        </div>
        <div class="float-right">
            <button type="submit" class="btn btn-secondary">Talep Oluştur</button>
        </div>
    </form>
</div>